apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: cache-volume
  containers:
  - image: almalinux:9
    name: almalinux
    volumeMounts:
    - mountPath: /mnt/nginx-logs
      name: cache-volume
      read only: true 
# This is at pod level      
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 500Mi