apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources: 
     # softlimit
    requests:
      memory: "64Mi" # RAM
      cpu: "100m" # CPU

      # hard limit
      limits:
        memory: "128" #RAM
        cpu: "150m" # CPU