apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  selector:
   # labels are used as selectors
   project: roboshop 
   component: frontend
   environment: dev
  ports:
  - protocol: TCP
    port: 80 # service port
    target port: 80 # container port